#!/usr/bin/env python3
import sys
sys.path.insert(0, '/usr/lib/touchpad-toggle')
import toggle
import evdev
from evdev import ecodes

conf = toggle.load_conf()
kbd = conf['KEYBOARD_EVENT']
device_path = kbd if kbd.startswith('/') else f'/dev/input/{kbd}'
device = evdev.InputDevice(device_path)
key_code = ecodes.ecodes[conf['TOGGLE_KEY']]

for event in device.read_loop():
    if event.type == ecodes.EV_KEY and event.code == key_code and event.value == 1:
        toggle.do_toggle()
